blogger/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('web.urls', namespace='web'))
]
if settings.DEBUG:
    urlpatterns += (
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) +
        static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    )

web/urls.py
from django.urls import path
from web import views

app_name = 'web'

urlpatterns = [
    path('',views.index, name="index"),
    path('login/',views.login, name="login"),
    path('register/',views.register, name="register"),
    path('logout/',views.logout, name="logout"),

    path('create/',views.create, name="create"),
    path('blog/<int:id>/',views.blog, name="blog"),

    path('blog/delete/<int:id>/',views.blog_delete, name="blog_delete"),

    path('account/',views.account, name="account"),

]

main/models.py
from django.db import models

# Create your models here.

users/models.py
from django.db import models
from django.contrib.auth.models import User

class Auther(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    class Meta:
        db_table = "users_auther"
        verbose_name = "auther"
        verbose_name_plural = "authers"
        ordering = ["-id"]

    def __str__(self):
        return self.user.username

web/models.py
from django.db import models
from users.models import Auther

class Category(models.Model):
    name = models.CharField(max_length=225)

    class Meta:
        db_table = "web_category"
        verbose_name = "category"
        verbose_name_plural = "categories"
        ordering = ["-id"]

    def __str__(self):
        return self.name
    
class Tag(models.Model):
    name = models.CharField(max_length=225)

    class Meta:
        db_table = "web_tag"
        verbose_name = "tag"
        verbose_name_plural = "tags"
        ordering = ["-id"]

    def __str__(self):
        return self.name

class Blog(models.Model):
    title = models.CharField(max_length=225)
    short_discription = models.CharField(max_length=225)
    image = models.ImageField(upload_to="blogs")
    created_on = models.DateTimeField(auto_now=True)
    discription = models.TextField()
    author = models.ForeignKey(Auther, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    tags = models.ManyToManyField(Tag)


    class Meta:
        db_table = "web_blog"
        verbose_name = "blog"
        verbose_name_plural = "blogs"
        ordering = ["-id"]

    def __str__(self):
        return self.title

main/views.py
from django.shortcuts import render

# Create your views here.

users/views.py
from django.shortcuts import render

# Create your views here.

web/views.py
from django.shortcuts import render,reverse
from django.http.response import HttpResponseRedirect
from django.contrib.auth import authenticate, login as auth_login, logout as auth_logout
from django.contrib.auth.decorators import login_required

from django.contrib.auth.models import User
from users.models import Auther
from web.models import Category, Blog, Tag

def index(request):
    categories = Category.objects.all()
    blogs = Blog.objects.all()

    authors = Auther.objects.all()
    tags = Tag.objects.all()

    context = {
        "categories": categories,
        "blogs": blogs,
        "authors": authors,
        "tags": tags,
    }
    return render(request, 'web/index.html', context=context)

def login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(request, username=username, password=password)

        if user is not None:
            auth_login(request, user)

            return HttpResponseRedirect(reverse('web:index'))
        
        else:
            return render(request, 'web/login.html')
    else:
        return render(request, 'web/login.html')
    
def register(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        first_name = request.POST.get('first_name')
        last_name = request.POST.get('last_name')
        password = request.POST.get('password')


        user = User.objects.create_user(
            username=username,
            first_name=first_name,
            last_name=last_name,
            password=password,
        )

        user.save()

        auther = Auther.objects.create(
        user=user,
        )
        auther.save()


        return HttpResponseRedirect(reverse('web:login'))
    
    else:
         return render(request, 'web/register.html')



def logout(request):
    user = request.user
    auth_logout(request)
    
    return HttpResponseRedirect(reverse('web:index'))


@login_required(login_url='/login')
def create(request):
    user = request.user
    auther = Auther.objects.get(user=user)
    categories = Category.objects.all()

    if request.method == 'POST':
        title = request.POST.get('title')
        image = request.FILES.get('image')
        short_discription = request.POST.get('short_discription')
        discription = request.POST.get('discription')
        category = request.POST.get('category')

        category = Category.objects.get(id=category)

        blog = Blog.objects.create(
            title=title,
            short_discription=short_discription,
            image=image,
            discription=discription,
            category=category,
            auther=auther,

        )
        blog.save()
        
        return HttpResponseRedirect(reverse('web:index'))


    else:

      context = {
        "categories":categories
      }
      return render(request, 'web/create.html', context=context)
    
def blog(request, id):
    blog = Blog.objects.get(id=id)
    blogs = Blog.objects.all()[:5]

    context = {
    "blog":blog,
    "blogs":blogs
    }
    return render(request, 'web/blog.html', context=context)


@login_required(login_url='/login')
def account(request):
    user = request.user
    auther = Auther.objects.get(user=user)

    blogs = Blog.objects.filter(author=auther)
    context = {
        "blogs":blogs
    }
    return render(request, 'web/account.html', context=context)

@login_required(login_url='/login')
def blog_delete(request, id):
    blog = Blog.objects.get(id=id)
    blog.delete()
    
    return HttpResponseRedirect(reverse('web:account'))

templates/base/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="favicon.ico" type="image/x-icon">
    <title>Blogger</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>

    {% block container %}
    
    {% endblock %}
    
</body>
</html>

templates/includes/header.html
{% load static %}
<header>
    <section class="wrapper">
        <div class="left">
            <h1><a href="{% url 'web:index' %}"><img src="{% static 'images/logo.png' %}" alt="logo"></a></h1>
        </div>
        <div class="middle">
            <form action="">
                <div>
                    <input type="search" placeholder="Search blog...">
                    <img src="{% static 'images/search.png' %}" alt="search" />
                </div>
            </form>
        </div>
        <div class="right">
            <ul>
                <li><a href="{% url 'web:index' %}">Home</a></li>
                <li><a href="{% url 'web:create' %}">Create</a></li>
                <li><a href="{% url 'web:account' %}">Account</a></li>
                {% if user.is_authenticated %}
                <li><a href="{% url 'web:logout' %}">Logout</a></li>
                {% else %}
                <li><a href="{% url 'web:login' %}">Login</a></li>
                {% endif %}
            </ul>
        </div>
    </section>
</header>

templates/web/account.html
{% extends 'base/base.html' %}

{% block container %}

{% include 'includes/header.html' %}

{% load static %}

    <section id="blog-list">
        <section class="wrapper">
            <div class="top">
                <h1>My Blogs</h1>
                <a href="{% url 'web:create' %}">Create</a>
            </div>
            <table>
                <thead>
                    <tr>
                        <th>Image</th>
                        <th>Title</th>
                        <th>Date</th>
                        <th>View</th>
                        <th>Edit</th>
                        <th>Delete</th>
                    </tr>
                </thead>
                <tbody>
                    {% for blog in blogs %}
                    <tr>
                        <td>
                            <img src="{{blog.image.url}}" alt="blog">
                        </td>
                        <td>{{blog.title}}</td>
                        <td>{{blog.created_on}}</td>
                        <td>
                            <a href="{% url 'web:blog' id=blog.id %}" class="view">View</a>
                        </td>
                        <td>
                            <a href="#" class="edit">Edit</a>
                        </td>
                        <td>
                            <a href="{% url 'web:blog_delete' id=blog.id %}" class="delete">Delete</a>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
            <div class="bottom">
                <div class="pagination">
                    <a href="#" class="prev">
                        <img src="{% static 'images/left-arrow.png' %}" alt="prev">
                    </a>
                    <a href="#" class="active">1</a>
                    <a href="#">2</a>
                    <span>...</span>
                    <a href="#">7</a>
                    <a href="#">8</a>
                    <a href="#" class="next">
                        <img src="{% static 'images/right-arrow.png' %}" alt="next">
                    </a>
                </div>
            </div>
        </section>
    </section>


{% endblock %}

templates/web/blog.html
{% extends 'base/base.html' %}

{% block container %}

{% include 'includes/header.html' %}

    <section id="blog-details">
        <section class="wrapper">
            <div class="left">
                <h1>{{blog.title}}</h1>
                <p>{{blog.short_discription}}</p>
                <div>
                    <p>{{blog.author.user.first_name}} {{blog.author.user.last_name}}</p>
                    <p>{{blog.created_on}}</p>
                </div>
                <img src="{{blog.image.url}}" alt="blog">
                <p>{{blog.discription}}</p>
            </div>
            <div class="right">
                <h3>Recent Blogs</h3>
                {% for blog in blogs %}
                <div>
                    <img src="{{blog.image.url}}" alt="blog">
                    <a href="{% url 'web:blog' id=blog.id %}">
                        <h3>{{blog.title}}</h3>
                    </a>
                </div>
                {% endfor %}
            </div>
        </section>
    </section>


{% endblock %}

templates/web/create.html
{% extends 'base/base.html' %}

{% block container %}

{% include 'includes/header.html' %}

    <section id="create">
        <section class="wrapper">
            <h1>Create a new blog</h1>
            <form action="" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form-control">
                    <input type="text" name="title" placeholder="Enter title">
                </div>
                <div class="form-control">
                    <label for="blog-image">Featured Image:</label>
                    <input type="file" name="image" id="blog-image">
                </div>
                <div class="form-control">
                    <input type="text" name="short_discription" placeholder="Enter short description">
                </div>
                <div class="form-control">
                    <select name="category" id="">
                        {% for category in categories %}
                        <option value="{{category.id}}">{{ category.name}}</option>
                        {% endfor %}
                    </select>
                </div>
                <!-- <div class="form-control">
                    <input type="text" placeholder="Enter tags (seperate using comma)"> -->
                </div>
                <div class="form-control">
                    <textarea name="discription" id="" cols="30" rows="10" placeholder="Enter blog"></textarea>
                </div>
                <div class="btn">
                    <input type="submit" value="Create">
                </div>
            </form>
        </section>
    </section>


{% endblock %}

templates/web/index.html
{% extends 'base/base.html' %}

{% block container %}

{% load static %}

{% include 'includes/header.html' %}

    <section id="category">
        <section class="wrapper">
            <ul>
                {% for category in categories %}
                <li><a class="active" href="#">{{category.name}}</a></li>
                {% endfor %}
            </ul>
        </section>
    </section>

    <section id="blogs">
        <section class="wrapper">
            <div class="left">
                <div class="top">
                    {% for blog in blogs %}
                    <div class="card">
                        <img src="{{blog.image.url}}" alt="blog-image">
                        <h3>
                            <a href="{% url 'web:blog' id=blog.id %}">{{blog.title}}</a>
                        </h3>
                        <div>
                            <span>{{blog.author.user.first_name}} {{blog.author.user.last_name}}</span>
                            <span>{{blog.created_on}}</span>
                        </div>
                        <p>{{blog.short_discription}}</p>
                        <ul>
                            {% for tag in blog.tags.all %}
                            <li>{{tag.name}}</li>
                            {% endfor %}
                        </ul>
                    </div>
                    {% endfor %}
                </div>
                <div class="bottom">
                    <div class="pagination">
                        <a href="#" class="prev">
                            <img src="{% static 'images/left-arrow.png' %}" alt="prev">
                        </a>
                        <a href="#" class="active">1</a>
                        <a href="#">2</a>
                        <span>...</span>
                        <a href="#">7</a>
                        <a href="#">8</a>
                        <a href="#" class="next">
                            <img src="{% static 'images/right-arrow.png' %}" alt="next">
                        </a>
                    </div>
                </div>
            </div>

            <div class="right">
                <h1>Fiter Blogs</h1>
                <form action="">
                    <div class="sort">
                        <h3>Sort by</h3>
                        <div>
                            <input type="radio" name="" id="">
                            <span>Recently Added</span>
                        </div>
                        <div>
                            <input type="radio" name="" id="">
                            <span>A-Z Ascending</span>
                        </div>
                        <div>
                            <input type="radio" name="" id="">
                            <span>A-Z Descending</span>
                        </div>
                    </div>
                    <div class="author">
                        <h3>By Author</h3>
                        {% for author in authors %}
                        <div>
                            <input type="checkbox" name="" id="">
                            <span>{{author.user.first_name}} {{author.user.last_name}}</span>
                        </div>
                        {% endfor %}
                    </div>
                    <div class="tags">
                        <h3>By Tags</h3>
                        {% for tag in tags %}
                        <div>
                            <input type="checkbox" name="" id="">
                            <span>{{tag.name}}</span>
                        </div>
                        {% endfor %}
                    </div>
                    <div class="submit">
                        <input type="submit" value="Filter">
                    </div>
                </form>
            </div>
        </section>
    </section>
    
    {% endblock %}

templates/web/login.html
{% extends 'base/base.html' %}

{% block container %}

{% load static %}

    <section id="login">
        <section class="wrapper">
            <div class="container">
                <form action="" method="post">
                    {% csrf_token %}
                    <div class="logo">
                        <img src="{% static './images/logo.png' %}" alt="logo" />
                    </div>
                    <h1>Login Now</h1>
                    <div class="form-control">
                        <input type="text" name="username" id="" placeholder="Enter username">
                    </div>
                    <div class="form-control">
                        <input type="password" name="password" id="" placeholder="Enter password">
                    </div>
                    <p>Don't have an account? <a href="{% url 'web:register' %}">Register</a></p>
                    <div class="btn">
                        <input type="submit" value="Login">
                    </div>
                </form>
            </div>
        </section>
    </section>
    
{% endblock %}

templates/web/register.html
{% extends 'base/base.html' %}

{% block container %}

{% load static %}

    <section id="login">
        <section class="wrapper">
            <div class="container">
                <form action="" method="post">
                    {% csrf_token %}
                    <div class="logo">
                        <img src="{% static './images/logo.png' %}" alt="logo" />
                    </div>
                    <h1>Create Account</h1>
                    <div class="form-control">
                        <input type="text" name="username" id="" placeholder="Enter username">
                    </div>
                    <div class="form-control">
                        <input type="text" name="first_name" id="" placeholder="Enter first name">
                    </div>
                    <div class="form-control">
                        <input type="text" name="last_name" id="" placeholder="Enter last name">
                    </div>
                    <div class="form-control">
                        <input type="password" name="password" id="" placeholder="Enter password">
                    </div>
                    <p>Already have an account? <a href="{% url 'web:login' %}">Login</a></p>
                    <div class="btn">
                        <input type="submit" value="Register">
                    </div>
                </form>
            </div>
        </section>
    </section>
    
{% endblock %}